//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class baitaplonmhEntities : DbContext
    {
        public baitaplonmhEntities()
            : base("name=baitaplonmhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bo_cau_hoi> bo_cau_hoi { get; set; }
        public virtual DbSet<cau_hoi_01> cau_hoi_01 { get; set; }
        public virtual DbSet<cau_hoi_02> cau_hoi_02 { get; set; }
        public virtual DbSet<cau_hoi_03> cau_hoi_03 { get; set; }
        public virtual DbSet<cau_hoi_04> cau_hoi_04 { get; set; }
        public virtual DbSet<cau_hoi_05> cau_hoi_05 { get; set; }
        public virtual DbSet<cau_hoi_06> cau_hoi_06 { get; set; }
        public virtual DbSet<cau_hoi_07> cau_hoi_07 { get; set; }
        public virtual DbSet<cau_hoi_08> cau_hoi_08 { get; set; }
        public virtual DbSet<cau_hoi_09> cau_hoi_09 { get; set; }
        public virtual DbSet<cau_hoi_10> cau_hoi_10 { get; set; }
    }
}
