//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bo_cau_hoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bo_cau_hoi()
        {
            this.cau_hoi_01 = new HashSet<cau_hoi_01>();
            this.cau_hoi_10 = new HashSet<cau_hoi_10>();
            this.cau_hoi_02 = new HashSet<cau_hoi_02>();
            this.cau_hoi_03 = new HashSet<cau_hoi_03>();
            this.cau_hoi_04 = new HashSet<cau_hoi_04>();
            this.cau_hoi_05 = new HashSet<cau_hoi_05>();
            this.cau_hoi_06 = new HashSet<cau_hoi_06>();
            this.cau_hoi_07 = new HashSet<cau_hoi_07>();
            this.cau_hoi_08 = new HashSet<cau_hoi_08>();
            this.cau_hoi_09 = new HashSet<cau_hoi_09>();
        }
    
        public string Ma_bo_cau_hoi { get; set; }
        public string Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cau_hoi_01> cau_hoi_01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cau_hoi_10> cau_hoi_10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cau_hoi_02> cau_hoi_02 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cau_hoi_03> cau_hoi_03 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cau_hoi_04> cau_hoi_04 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cau_hoi_05> cau_hoi_05 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cau_hoi_06> cau_hoi_06 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cau_hoi_07> cau_hoi_07 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cau_hoi_08> cau_hoi_08 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cau_hoi_09> cau_hoi_09 { get; set; }
    }
}
