//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cau_hoi_04
    {
        public string Ma_cau_hoi { get; set; }
        public string Ma_bo_cau_hoi { get; set; }
        public string Noi_Dung { get; set; }
        public string Dap_An_A { get; set; }
        public string Dap_An_B { get; set; }
        public string Dap_An_C { get; set; }
        public string Dap_An_D { get; set; }
        public string Dap_An_Dung { get; set; }
    
        public virtual bo_cau_hoi bo_cau_hoi { get; set; }
    }
}
